### ISSUE TITLE
Ctrl-C only kill the first process

### ISSUE THREAD

**Issue by alicoding** [keithamus/parallelshell#12]
I'm using `parallelshell` in `npm script` right now and it's working great, but the only problem I'm having right now is that when I run three commands using `parallelshell` and when hit `Ctrl-C` it will only kill the first process and left the other two running in the foreground.

```
    "start": "parallelshell \"npm run serve\" \"npm run watch-css\" \"npm run watch-js\"",
```

Where as doing:
```
    "start": "npm run serve & npm run watch-css & npm run watch-js",
```

The above command will kill all three completely when you hit `Ctrl-C`.

I'm not sure if this is a bug but trying to figure out how to deal with this.

**Comment by keithamus** [comment]
Thanks for the issue @alicoding, it's definitely a bug; Ctrl+C should kill all three. 

They should be registered as children of the process and my understanding of unix is that killing a parent kills all children. Maybe this assumption is wrong.

I guess the brute-force(ish) way to do this is listen for the TERM signal and manually dispatch it to all other processes. Maybe we should be generically doing this anyway?

**Comment by jbuck** [comment]
I was digging into this with @alicoding and we found that the problem was actually when you have a parallelshell child process exit with non-zero status code. It doesn't kill the other parallelshell child processes. Here's an example with a dummy sleep script:

```
Jons-MacBook-Pro:nsleep jbuck$ ./node_modules/.bin/parallelshell "node index.js 1000 1" "node index.js 10000 0"
nsleep.pid = 13373, sleeping for 10000ms
nsleep.pid = 13372, sleeping for 1000ms
nsleep.pid = 13372, slept for 1000ms
`node index.js 1000 1` failed with exit code 1
Jons-MacBook-Pro:nsleep jbuck$ ps
  PID TTY           TIME CMD
13006 ttys003    0:00.06 -bash
13373 ttys003    0:00.08 node index.js 10000 0
Jons-MacBook-Pro:nsleep jbuck$ nsleep.pid = 13373, slept for 10000ms
ps
  PID TTY           TIME CMD
13006 ttys003    0:00.06 -bash
Jons-MacBook-Pro:nsleep jbuck$
```

I also thought that if the parent process dies the child processes die so I'm not sure why it's continuing to run in the background

**Comment by jbuck** [comment]
Also, this exactly matches the behaviour of the `&` operator.

If you use the `wait` command, then you have to wait for all processes to exit before getting the terminal prompt which is more intuitive:

`node index.js 1000 1 & node index.js 5000 0 & wait`

**Comment by jbuck** [comment]
Should parallelshell kill all child processes when one of them exits with a non-zero error code? I think it's more intuitive, but it is a different behaviour. Maybe put it behind some sort of a flag, -w/--wait so it kinda acts like the bash `wait` built-in?

**Comment by keithamus** [comment]
The original design intention was for parallelshell to close all child processes every time if either one of the processes died, or you killed the parallelshell task. This is primarily because if you're killing it, or another process died - things have probably gotten messed up and you're going to re-run it all anyway. Most stuff behind parallelshell will either be build scripts or something like nodemon - so making it kill everything doesn't end the world, as you can get back to where you were by just re-running the command.

However, if you have a better idea (which it sounds like you do with `-w`) then I'd love to see a PR. I guess what I'd like to see is: default behaviour kills all processes on crash or kill, adding `-w` will wait until all processes finish or crash, ctrl+c kills all regardless of `-w`.

**Comment by paulpflug** [comment]
hey, I could build something, but if it comes to parsing args - you mind the use of commander or similar helpers?

**Comment by keithamus** [comment]
I'd rather keep this to 0 dependencies, but if you absolutely need to - go for it.

**Comment by anler** [comment]
Hi all, any plan on merging the fix? I need this! :smile:

**Comment by radekskrabal** [comment]
Hi guys, I love using <code>parallelshell</code> on <code>Windows</code>. I would really appreciate if you could merge the PR.

**Comment by keithamus** [comment]
PR can be merged when notes are addressed. Feel free to take the contents of the PR and make the changes yourself, then submit a new PR.

**Comment by chaines** [comment]
It appears a pull request was merged to fix this issue, issue should be closed?

**Comment by keithamus** [comment]
:+1:
